EVALUATE
SUMMARIZE(
    ADDCOLUMNS(
        Orders,
        "Year", YEAR(Orders[Order Date]),     -- Add a Year column
        "Month", MONTH(Orders[Order Date]),
        "Day", DAY(Orders[Order Date])		 -- Add a Month column
    ),
    [Year],                                  -- Group by Year
    [Month],  
    [Day],									-- Group by Month
    "Count of Dates", COUNTROWS(Orders)      -- Count rows in each group
)

EVALUATE
SUMMARIZE(
    Orders,                     -- Source table
    Orders[Order Date],         -- Group by the Order Date
    "Number of Dates", COUNTROWS(Orders),   -- Count occurrences of each date
    "Total Sales", SUM(Orders[Sales])       -- Calculate the total sales for each date
)

EVALUATE
CALCULATETABLE(
	Orders,
	Orders[Ship Mode] = "Standard Class",
	Orders[Sales] >= 1500
	)
	

EVALUATE
SELECTCOLUMNS(
    CALCULATETABLE(
        Orders,
        Orders[Ship Mode] = "Standard Class",  -- Filter rows where Ship Mode is Standard Class
        Orders[Sales] >= 1500                 -- Filter rows where Sales >= 1500
    ),
    "Order Date", Orders[Order Date],         -- Select Order Date column
    "Ship Mode", Orders[Ship Mode],           -- Select Ship Mode column
    "Customer Name", Orders[Customer Name],    -- Select Customer Name column
    "Sales", Orders[Sales]
)

EVALUATE
SUMMARIZE(
    Orders,                     -- Source table
    Orders[Product Name],         -- Group by the Product Name
    "Number of Products", COUNTROWS(Orders),   -- Count occurrences of product
    "Total Sales", SUM(Orders[Sales])       -- Calculate the total sales for product
)

EVALUATE
SUMMARIZE(
    Orders,                     -- Source table
    Orders[Category],         -- Group by the Category
    "Categories", COUNTROWS(Orders),   -- Count occurrences of category
    "Total Sales", SUM(Orders[Sales])       -- Calculate the total sales for each category
)