EVALUATE
SUMMARIZE(
    ADDCOLUMNS(
        Orders,
        "Year", YEAR(Orders[Order Date]),     -- Add a Year column
        "Month", MONTH(Orders[Order Date]),
        "Day", DAY(Orders[Order Date])		 -- Add a Month column
    ),
    [Year],                                  -- Group by Year
    [Month],  
    [Day],									-- Group by Month
    "Count of Dates", COUNTROWS(Orders)      -- Count rows in each group
)

EVALUATE
SUMMARIZE(
    Orders,                     -- Source table
    Orders[Order Date],         -- Group by the Order Date
    "Number of Dates", COUNTROWS(Orders),   -- Count occurrences of each date
    "Total Sales", SUM(Orders[Sales])       -- Calculate the total sales for each date
)

EVALUATE
CALCULATETABLE(
	Orders,
	Orders[Ship Mode] = "Standard Class",
	Orders[Sales] >= 1500
	)
	

EVALUATE
SELECTCOLUMNS(
    CALCULATETABLE(
        Orders,
        Orders[Ship Mode] = "Standard Class",  -- Filter rows where Ship Mode is Standard Class
        Orders[Sales] >= 1500                 -- Filter rows where Sales >= 1500
    ),
    "Order Date", Orders[Order Date],         -- Select Order Date column
    "Ship Mode", Orders[Ship Mode],           -- Select Ship Mode column
    "Customer Name", Orders[Customer Name],    -- Select Customer Name column
    "Sales", Orders[Sales]
)

EVALUATE
SUMMARIZE(
    Orders,                     -- Source table
    Orders[Product Name],         -- Group by the Product Name
    "Number of Products", COUNTROWS(Orders),   -- Count occurrences of product
    "Total Sales", SUM(Orders[Sales])       -- Calculate the total sales for product
)

EVALUATE
SUMMARIZE(
    Orders,                     -- Source table
    Orders[Category],         -- Group by the Category
    "Categories", COUNTROWS(Orders),   -- Count occurrences of category
    "Total Sales", SUM(Orders[Sales])       -- Calculate the total sales for each category
)

EVALUATE
SUMMARIZE(
    Orders,                     -- Source table
    Orders[Sub-Category],         -- Group by the Sub Category
    "Sub Category", COUNTROWS(Orders),   -- Count occurrences of subcategory
    "Total Sales", SUM(Orders[Sales])       -- Calculate the total sales for each sub category
)

EVALUATE
TOPN(
    3,                                     -- Return the top 3 rows
    SUMMARIZE(
        Orders,                            -- Source table
        Orders[Sub-Category],             -- Group by Sub-Category
        "Sub Category", COUNTROWS(Orders),-- Count occurrences of subcategory
        "Total Sales", SUM(Orders[Sales]) -- Calculate total sales for each subcategory
    ),
    [Total Sales],                        -- Sort by Total Sales
    DESC                                  -- Sort in descending order
)

EVALUATE VALUES(Orders[Category])

EVALUATE
CALCULATETABLE(
    Orders,                             -- Base table
    Orders[Category] = "Technology",   -- Filter: Only Electronics category
    Orders[Sales] > 1000                -- Filter: Sales greater than 1000
)

EVALUATE
SELECTCOLUMNS(
	CALCULATETABLE(
	    Orders,                             -- Base table
	    Orders[Category] = "Technology",   -- Filter: Only Electronics category
	    Orders[Sales] > 1000                -- Filter: Sales greater than 1000
	),
	Orders[Product Name],
	Orders[Sales]
)

EVALUATE                                  -- Used to execute and return the result of a table expression
SUMMARIZE(                                -- Aggregates data by grouping and calculating
    Orders,                               -- Base table to summarize
    Orders[Product Name],
    "Total Sales", SUM(Orders[Sales]),    -- Grouping column: Groups the data by Product Name
    "Total Per Product",                  -- Name of the calculated column in the summarized table
    COUNTROWS(Orders)                     -- Calculation: Counts the number of rows for each Product Name
)


EVALUATE         
TOPN(
    10,                                     -- Top 10 rows
    SUMMARIZE(                             
        Orders,                            
        Orders[Product Name],              
        "Total Sales", SUM(Orders[Sales]), -- Total sales per product
        "Total Per Product",               
        COUNTROWS(Orders)                  -- Total number of orders per product
    ),
    [Total Sales],                          -- Ranking criteria (Total Sales)
    DESC                                    -- Descending order
)


EVALUATE
TOPN(10,	-- Used to execute and return the result of a table expression
SUMMARIZE(                                -- Aggregates data by grouping and calculating
    Orders,                               -- Base table to summarize
    Orders[Product Name],
    "Total Sales", SUM(Orders[Sales]),    -- Grouping column: Groups the data by Product Name
    "Total Per Product",                  -- Name of the calculated column in the summarized table
    COUNTROWS(Orders)                     -- Calculation: Counts the number of rows for each Product Name
)
)

EVALUATE
    SUMMARIZE(
        Orders, 
        Orders[Product Name],                   -- Group by Product Name
        "Product Count", COUNTROWS(Orders), 
        "Total Sales", SUM(Orders[Sales])       -- Count the number of rows for each product
    )
ORDER BY
	[Product Count] DESC
	
	
EVALUATE
    SUMMARIZE(
        Orders, 
        Orders[Product Name],                   -- Group by Product Name
        "Product Count", COUNTROWS(Orders), 
        "Total Sales", SUM(Orders[Sales])       -- Calculate the total sales for each product
    )
ORDER BY
    [Total Sales] DESC                          -- Sort by Total Sales in descending order
    
    
EVALUATE
	TOPN(10,
    SUMMARIZE(
        Orders, 
        Orders[Product Name],                   -- Group by Product Name
        "Product Count", COUNTROWS(Orders), 
        "Total Sales", SUM(Orders[Sales])       -- Calculate the total sales for each product
    )
   )  

EVALUATE
    TOPN(
        10,                                      -- Return the top 10 rows
        SUMMARIZE(
            Orders, 
            Orders[Product Name],                -- Group by Product Name
            "Product Count", COUNTROWS(Orders), 
            "Total Sales", SUM(Orders[Sales])    -- Calculate the total sales for each product
        ),
        [Total Sales],                           -- Rank by Total Sales
        DESC                                     -- Descending order
    )
    

EVALUATE
    SUMMARIZE(
        Orders, 
        Orders[Product Name],                   -- Group by Product Name
        "Product Count", COUNTROWS(Orders), 
        "Total Sales", SUM(Orders[Sales])       -- Calculate the total sales for each product
    )
ORDER BY
    [Total Sales] DESC 



EVALUATE
    TOPN(
        3,                                      -- Top 3 rows
        SUMMARIZE(
            Orders, 
            Orders[Category],                   -- Group by Category
            Orders[Product Name],               -- Group by Product Name
            "Total Sales", SUM(Orders[Sales])   -- Calculate total sales for each product
        ),
        [Total Sales],                          -- Rank by Total Sales
        DESC                                    -- Descending order
    )

EVALUATE
CALCULATETABLE(
	SUMMARIZE(Orders,
			  Orders[Sub-Category]
	)
)

EVALUATE
SUMMARIZE(Orders,
		  Orders[Sub-Category]
		  )
		  
EVALUATE
CALCULATETABLE(
	VAR Variable = SUMMARIZE(Orders,
			  Orders[Sub-Category]
	)
	RETURN Variable
)

EVALUATE
CALCULATETABLE(
    VAR Variable = SUMMARIZE(Orders, Orders[Sub-Category])
    RETURN Variable
)