EVALUATE
SUMMARIZE(
    ADDCOLUMNS(
        Orders,
        "Year", YEAR(Orders[Order Date]),     -- Add a Year column
        "Month", MONTH(Orders[Order Date]),
        "Day", DAY(Orders[Order Date])		 -- Add a Month column
    ),
    [Year],                                  -- Group by Year
    [Month],  
    [Day],									-- Group by Month
    "Count of Dates", COUNTROWS(Orders)      -- Count rows in each group
)

EVALUATE
SUMMARIZE(
    Orders,                     -- Source table
    Orders[Order Date],         -- Group by the Order Date
    "Number of Dates", COUNTROWS(Orders),   -- Count occurrences of each date
    "Total Sales", SUM(Orders[Sales])       -- Calculate the total sales for each date
)