EVALUATE
SUMMARIZE(
    ADDCOLUMNS(
        Orders,
        "Year", YEAR(Orders[Order Date]),     -- Add a Year column
        "Month", MONTH(Orders[Order Date]),
        "Day", DAY(Orders[Order Date])		 -- Add a Month column
    ),
    [Year],                                  -- Group by Year
    [Month],  
    [Day],									-- Group by Month
    "Count of Dates", COUNTROWS(Orders)      -- Count rows in each group
)

EVALUATE
SUMMARIZE(
    Orders,                     -- Source table
    Orders[Order Date],         -- Group by the Order Date
    "Number of Dates", COUNTROWS(Orders),   -- Count occurrences of each date
    "Total Sales", SUM(Orders[Sales])       -- Calculate the total sales for each date
)

EVALUATE
CALCULATETABLE(
	Orders,
	Orders[Ship Mode] = "Standard Class",
	Orders[Sales] >= 1500
	)
	

EVALUATE
SELECTCOLUMNS(
    CALCULATETABLE(
        Orders,
        Orders[Ship Mode] = "Standard Class",  -- Filter rows where Ship Mode is Standard Class
        Orders[Sales] >= 1500                 -- Filter rows where Sales >= 1500
    ),
    "Order Date", Orders[Order Date],         -- Select Order Date column
    "Ship Mode", Orders[Ship Mode],           -- Select Ship Mode column
    "Customer Name", Orders[Customer Name],    -- Select Customer Name column
    "Sales", Orders[Sales]
)

EVALUATE
SUMMARIZE(
    Orders,                     -- Source table
    Orders[Product Name],         -- Group by the Product Name
    "Number of Products", COUNTROWS(Orders),   -- Count occurrences of product
    "Total Sales", SUM(Orders[Sales])       -- Calculate the total sales for product
)

EVALUATE
SUMMARIZE(
    Orders,                     -- Source table
    Orders[Category],         -- Group by the Category
    "Categories", COUNTROWS(Orders),   -- Count occurrences of category
    "Total Sales", SUM(Orders[Sales])       -- Calculate the total sales for each category
)

EVALUATE
SUMMARIZE(
    Orders,                     -- Source table
    Orders[Sub-Category],         -- Group by the Sub Category
    "Sub Category", COUNTROWS(Orders),   -- Count occurrences of subcategory
    "Total Sales", SUM(Orders[Sales])       -- Calculate the total sales for each sub category
)

EVALUATE
TOPN(
    3,                                     -- Return the top 3 rows
    SUMMARIZE(
        Orders,                            -- Source table
        Orders[Sub-Category],             -- Group by Sub-Category
        "Sub Category", COUNTROWS(Orders),-- Count occurrences of subcategory
        "Total Sales", SUM(Orders[Sales]) -- Calculate total sales for each subcategory
    ),
    [Total Sales],                        -- Sort by Total Sales
    DESC                                  -- Sort in descending order
)

EVALUATE VALUES(Orders[Category])

EVALUATE
CALCULATETABLE(
    Orders,                             -- Base table
    Orders[Category] = "Technology",   -- Filter: Only Electronics category
    Orders[Sales] > 1000                -- Filter: Sales greater than 1000
)

EVALUATE
SELECTCOLUMNS(
	CALCULATETABLE(
	    Orders,                             -- Base table
	    Orders[Category] = "Technology",   -- Filter: Only Electronics category
	    Orders[Sales] > 1000                -- Filter: Sales greater than 1000
	),
	Orders[Product Name],
	Orders[Sales]
)

EVALUATE                                  -- Used to execute and return the result of a table expression
SUMMARIZE(                                -- Aggregates data by grouping and calculating
    Orders,                               -- Base table to summarize
    Orders[Product Name],                 -- Grouping column: Groups the data by Product Name
    "Total Per Product",                  -- Name of the calculated column in the summarized table
    COUNTROWS(Orders)                     -- Calculation: Counts the number of rows for each Product Name
)
